### PR TITLE
ENH: updates to make module work with python 3

### PR DESCRIPTION
**Pull request by fedorov**
depends on https://github.com/QIICR/SlicerDevelopmentToolbox/pull/36

### CODE REVIEW

**Comment by fedorov** [comment]
@che85 do you have any idea how to fix this error:

image

**Comment by che85** [comment]
What versions of Slicer and the repositories are you using? That way, it might be easier to reproduce on my side

**Comment by fedorov** [comment]
Today's nightly with this branch, and SDR branch mentioned above.

**Comment by fedorov** [comment]
Yes, I agree - those were added automatically by that modernizer package I mentioned in the SDT PR https://github.com/mitsuhiko/python-modernize. I thought it is probably more efficient to use that script instead of manually identifying and fixing one issue at a time, which I did to fix mpReview...

**Comment by che85** [comment]
@fedorov I added some code. The error was caused by ScriptedLoadableModule trying to get the modulePath for looking for resources. A new feature was added that automatically provides `resourcesPath` for any subclassed ScriptedLoadableModule

**Comment by fedorov** [comment]
Thanks Christian - working better now - next issue is this - happens if I examine a DICOM SEG instance:

image

**Comment by fedorov** [comment]
The above seemed to be fixed by the patch below using `python-modernizer`:

```
--- ./SlicerDevelopmentToolboxUtils/decorators.py	(original)
+++ ./SlicerDevelopmentToolboxUtils/decorators.py	(refactored)
@@ -1,8 +1,11 @@
+from __future__ import absolute_import
+from __future__ import print_function
 from functools import wraps
 import itertools
 import logging
 import inspect
 import slicer
+from six.moves import map


 class logmethod(object):
@@ -226,7 +229,7 @@

   def getStringifiedClasses(t):
     if type(t) is list:
-      return map(getStringifiedClasses, t)
+      return list(map(getStringifiedClasses, t))
     else:
       return t.__name__ if not type(t) is str else t

@@ -250,7 +253,7 @@
     startTime = time.time()
     x = func(*args, **kwargs)
     duration = time.time() - startTime
-    print("{} ran in: {0} seconds".format(func.__name__, duration))
+    print(("{} ran in: {0} seconds".format(func.__name__, duration)))
     return x

   return _new_function
```

**Pull request merged**
